### ISSUE TITLE
Display filename error and cannot detect m4a music file format

### ISSUE THREAD

**Issue by ghost** [RussianFedora/moc#1]
Hi,

I installed [moc-2.6-0.1.alpha2.fc24.R.x86_64.rpm](http://koji.russianfedora.pro/kojifiles/packages/moc/2.6/0.1.alpha2.fc24.R/x86_64/moc-2.6-0.1.alpha2.fc24.R.x86_64.rpm) from koji.russianfedora.pro, and got **two errors**:
1. **Cannot display file names correctly**. It displays "#" instead of the correct characters (see the screenshot below).
   ![screenshot from 2016-05-27 22-34-50](https://cloud.githubusercontent.com/assets/13869410/15608226/d863514c-245b-11e6-910e-b5f74db9a5f1.png)
2. **Cannot recognise m4a music file format**. It just leaves empty. (see the screenshot below). 
   ![screenshot from 2016-05-27 22-34-05](https://cloud.githubusercontent.com/assets/13869410/15608224/d85e6902-245b-11e6-945e-4409f4e6be05.png)

I had no idea why it happened. But I tried to reference moc pkgbuild from Archlinux, edit moc.spec file by modifying configure options, and rebuild the package; and everything worked! Errors disappeared!

Here is my configure options:

``` rpm
%configure \
       --prefix=/usr \
       --without-rcc \
       --with-oss \
       --with-alsa \
       --with-jack \
       --with-aac \
       --with-mp3 \
       --with-musepack \
       --with-vorbis \
       --with-flac \
       --with-wavpack \
       --with-sndfile \
       --with-modplug \
       --with-ffmpeg \
       --with-speex \
       --with-samplerate \
       --with-curl  \
       --disable-cache \
       --disable-debug
```

And the screenshot of running properly (using package built with modified configure options):

![screenshot from 2016-05-27 22-32-01](https://cloud.githubusercontent.com/assets/13869410/15608225/d85e9346-245b-11e6-9c42-607f8dab95f3.png)

The following screenshot is compared with the first one on the top.
![screenshot from 2016-05-27 22-59-42](https://cloud.githubusercontent.com/assets/13869410/15608676/c843b010-245e-11e6-93ff-e96ee604e8e8.png)

Hope it helps packaging moc package.

Thank you.

**Comment by ghost** [comment]
@nrechn hi

> Cannot recognise m4a music file format. It just leaves empty. 

![screenshot from 2016-05-27 16-20-54](https://cloud.githubusercontent.com/assets/13280183/15609192/3f2488ea-2427-11e6-9ea8-246a61cbb61f.png)

```
[maxim@localhost ~]$ rpm -qi moc
Name        : moc
Epoch       : 1
Version     : 2.6
Release     : 0.1.alpha2.fc23.R
Architecture: x86_64
Install Date: Fri 20 May 2016 10:36:25 PM MSK
Group       : Unspecified
Size        : 695593
License     : GPLv2+
Signature   : DSA/SHA1, Tue 10 May 2016 02:08:11 PM MSK, Key ID 8318be83dbb6c70d
Source RPM  : moc-2.6-0.1.alpha2.fc23.R.src.rpm
Build Date  : Tue 10 May 2016 12:30:35 PM MSK
Build Host  : koji-builder01
Relocations : (not relocatable)
Packager    : Koji
Vendor      : Russian Fedora Team
URL         : http://moc.daper.net/
Summary     : Music On Console
Description :
MOC (music on console) is a console audio player for LINUX/UNIX
designed to be powerful and easy to use.
```

everything is fine.

**Comment by ghost** [comment]
> Cannot display file names correctly. It displays "#" instead of the correct characters

link to a file?

**Comment by ghost** [comment]
"#" replaces the correct characters include Chinese characters and Japanese characters.

I am running Fedora 24. And I got the package directly from http://koji.russianfedora.pro/koji/buildinfo?buildID=3390

**Comment by ghost** [comment]
> "#" replaces the correct characters include Chinese characters and Japanese characters.

link to a music file

**Comment by ghost** [comment]
> link to a music file

Yes. It does. Just file name becomes "###".

**Comment by ghost** [comment]
Please upload one of this files.
I'll check.

**Comment by ghost** [comment]
~~[160511]TVアニメ「甲鉄城のカバネリ」EDテーマ「ninelie」／Aimer with chelly(EGOIST)[FLAC+CUE].zip~~

Thanks.

> Note: Removed the link of the file. It actually not allowed to be shared through Internet due to the copyright.

**Comment by ghost** [comment]
@nrechn 

> Cannot display file names correctly. It displays "#" instead of the correct characters
> 
> > "#" replaces the correct characters include Chinese characters and Japanese characters

fixed 58c5367e1d215f5df9c9f955710967f1a64150fc
![screenshot from 2016-05-27 20-35-08](https://cloud.githubusercontent.com/assets/13280183/15616193/d992abaa-244a-11e6-846b-76ccd51be182.png)

**Comment by ghost** [comment]
> Cannot recognise m4a music file format. It just leaves empty.

I can't reproduce.
https://github.com/RussianFedora/moc/issues/1#issuecomment-222145049

**Comment by region51** [comment]
@nrechn 
>and rebuild the package; and everything worked! Errors disappeared!

what version of ffmpeg used for rebuild?

**Comment by ghost** [comment]
@nrechn 

> and rebuild the package; and everything worked! Errors disappeared!

what version of ffmpeg used for rebuild?

**Comment by ghost** [comment]
> fixed 58c5367

Thanks for solving the issue.

> what version of ffmpeg used for rebuild?

Sorry，I forgot to mention ffmpeg version. It is ffmpeg-3.0.2.

> Cannot recognise m4a music file format. It just leaves empty.

It might be possible caused by building moc package with ffmpeg-3.0.2 instead of 2.8.
I am going to downgrade ffmpeg version and see if trhe problem is still there.

**Comment by ghost** [comment]
@region51 

I just downgraded ffmpeg and tested running moc with ffmpeg-2.8.7. And everything works well. 

> Cannot recognise m4a music file format. It just leaves empty.

Therefore, it seems like this problem only appears if using moc with ffmpeg-3.0.2.

**Comment by ghost** [comment]
> I just downgraded ffmpeg and tested running moc with ffmpeg-2.8.7. And everything works well.
> 
> > Therefore, it seems like this problem only appears if using moc with ffmpeg-3.0.2.

OK, ffmpeg-3.0.2 👎 . Thanks for the bug report.

**Comment by ghost** [comment]
Thanks for your response of the issue.

**Comment by ghost** [comment]
@nrechn 

> Therefore, it seems like this problem only appears if using moc with ffmpeg-3.0.2.

```
[maxim@localhost ~]$ rpm -q ffmpeg-libs moc
ffmpeg-libs-3.0.2-1.fc24.x86_64
moc-2.6-0.3.alpha2.fc24.R.x86_64

```

![screenshot from 2016-06-22 14-17-31](https://cloud.githubusercontent.com/assets/13280183/16264824/5dd92b8a-3884-11e6-9101-b5e3146e83ab.png)

F24, FFmpeg-3.0.2,  moc-2.6-alpha2 everything is fine with m4a music file format.
